-- seed data for test and troubleshooting
insert into users (username, password) values ('ned stark','WinterComes'), ('jonSNOW333','Knows nothing'), 
('DanyDragons','khaleesi'), ('KINGJOFFREY','KING'), ('reek','RhymeWithTeak'),('Tyrion Lanniser','theHand');

insert into players (user_id, name) values (1, 'ned stark'), (2, 'jonSNOW333'), (3, 'DanyDragons'), 
(4, 'KINGJOFFREY'), (5, 'reek'),(6, 'Tyrion Lanniser');

insert into games (player1_id, player2_id, player3_id, player4_id,life1, life2, life3, life4, duration, winner_id)    
values (6,4,null, null, 12,0,null,null,'00:20:30',6), (6,2,null, null, 5,0,null,null,'00:23:00',6),
(6,1,null, null, 1,0,null,null,'00:45:30',6), (3,2,null, null, 0,20,null,null,'00:20:30',2), 
(2,4,null, null, 12,0,null,null,'00:20:30',2), (6,4,null, null, 7,0,null,null,'00:20:30',6),
(4,1,null, null, 0,5,null,null,'00:20:30',1),(4,1,6,5,0,0,3,0,'01:12:30',6),
(6,1,null, null, 1,0,null,null,'00:45:30',6), (3,2,null, null, 0,20,null,null,'00:20:30',2), 
(2,4,null, null, 12,0,null,null,'00:20:30',2), (6,4,null, null, 7,0,null,null,'00:20:30',6),
(4,1,null, null, 0,5,null,null,'00:20:30',1),(4,1,6,5,0,0,3,0,'01:12:30',6)
;

insert into tokens (name, number_code, color, pt, promo, type, artist, text) 
values 
    ('Pegasus','89','W','1|1','-','Creature - Pegasus','Mark Zug','Flying'),
    ('Soldier','90','W','1|1','-','Creature - Soldier','Daren Bader','-'),
    ('Zombie','91','B','2|2','-','Creature - Zombie','Christopher Rush','-'),
    ('Goblin','92','R','1|1','-','Creature - Goblin','Pete Venters','-'),
    ('Sheep','93','G','-','-','Creature - Sheep','Kev Walker','-'),
    ('Squirrel','94','G','1|1','-','Creature - Squirrel','Ron Spencer','-'),
    ('Bird','T1','U','1|1','Player Rewards','Creature - Bird','Michael Sutfin','Flying'),
    ('Elephant','T2','G','3|3','Player Rewards','Creature - Elephant','Terese Nielsen','-'),
    ('Saproling','T3','G','1|1','Player Rewards','Creature - Saproling','Jeff Laubenstein','-'),
    ('Spirit','T1','W','1|1','Player Rewards','Creature - Spirit','John Matson','Flying'),
    ('Goblin Soldier','T1','R W','1|1','Player Rewards','Creature - Goblin Soldier','Ron Spears','-'),
    ('Bear','T1','G','2|2','Player Rewards','Creature - Bear','Heather Hudson','-'),
    ('Beast','T2','G','4|4','Player Rewards','Creature - Beast','Larry Elmore','-'),
    ('Elephant','T3','G','3|3','Player Rewards','Creature - Elephant','Arnie Swekel','-'),
    ('Squirrel','T4','G','1|1','Player Rewards','Creature - Squirrel','Ron Spencer','-'),
    ('Wurm','T5','G','6|6','Player Rewards','Creature - Wurm','Alan Pollack','-'),
    ('Zombie','T6','B','2|2','Player Rewards','Creature - Zombie','Dana Knutson','-'),
    ('Angel','1','W','4|4','10th Anniversary','Creature - Angel','Jonathon Earl Bowser','Flying'),
    ('Dragon','2','R','5|5','10th Anniversary','Creature - Dragon','Angus McBride','Flying'),
    ('Wurm','2','G','6|6','10th Anniversary','Creature - Wurm','Jeff Easley','-'),
    ('Elephant','3','G','3|3','10th Anniversary','Creature - Elephant','Alan Lee','-'),
    ('Soldier','4','W','1|1','10th Anniversary','Creature - Soldier','Angus McBride','-'),
    ('Squirrel','5','G','1|1','10th Anniversary','Creature - Squirrel','-','-'),
    ('Zombie','6','B','2|2','10th Anniversary','Creature - Zombie','Brom','-'),
    ('Bear','T1','G','2|2','Player Rewards','Creature - Bear','Glen Angus','-'),
    ('Dragon','T2','R','5|5','Player Rewards','Creature - Dragon','Glen Angus','Flying'),
    ('Insect','T3','G','1|1','Player Rewards','Creature - Insect','Anthony S. Waters','-'),
    ('Soldier','T4','W','1|1','Player Rewards','Creature - Soldier','Ron Spencer','-'),
    ('Goblin','T1','R','1|1','Player Rewards','Creature - Goblin','Darrell Riche','-'),
    ('Sliver','T2','-','1|1','Player Rewards','Creature - Sliver','Tony Szczudlo','-'),
    ('Angel','T1','W','4|4','Player Rewards','Creature - Angel','Scott M. Fischer','Flying'),
    ('Rukh','T1','R','4|4','Player Rewards','Creature - Rukh','Edward P. Beard‚ Jr.','Flying'),
    ('Demon','T1','B','*|*','Player Rewards','Creature - Demon','Pete Venters','-'),
    ('Myr','T2','-','1|1','Player Rewards','Artifact Creature - Myr','Wayne England','-'),
    ('Pentavite','T3','-','1|1','Player Rewards','Artifact Creature - Pentavite','Greg Staples','Flying'),
    ('Beast','T1','G','3|3','Player Rewards','Creature - Beast','Edward P. Beard‚ Jr.','-'),
    ('Spirit','T1','-','1|1','Player Rewards','Creature - Spirit','Hugh Jamieson','-'),
    ('Marit Lage','T1','B','20|20','Pre-Release','Creature - Avatar','Stephan Martiniere','Flying‚ indestructible'),
    ('Assembly-Worker','1','-','2|2','TakaraTomy','Artifact Creature - Assembly-Worker','Mark Tedin','-'),
    ('Citizen','2','W','1|1','TakaraTomy','Creature - Citizen','Michael Phillippi','-'),
    ('Elephant','3','G','3|3','TakaraTomy','Creature - Elephant','Lars Grant-West','-'),
    ('Griffin','4','W','2|2','TakaraTomy','Creature - Griffin','Jim Nelson','Flying'),
    ('Kobold','5','R','-','TakaraTomy','Creature - Kobold','Parente','-'),
    ('Pegasus','6','W','1|1','TakaraTomy','Creature - Pegasus','Greg Hildebrandt','Flying'),
    ('Saproling','7','G','1|1','TakaraTomy','Creature - Saproling','Warren Mahy','-'),
    ('Triskelavite','8','-','1|1','TakaraTomy','Artifact Creature - Triskelavite','Mark Zug','Flying Sacrifice Triskelavite: Triskelavite deals 1 damage to target creature or player'),
    ('Wurm','9','G','*|*','TakaraTomy','Creature - Wurm','Jeff Easley','-'),
    ('Soldier','1','W','1|1','-','Creature - Soldier','Parente','-'),
    ('Zombie','2','B','2|2','-','Creature - Zombie','Carl Critchlow','-'),
    ('Dragon','3','R','5|5','-','Creature - Dragon','Jim Pavelec','Flying'),
    ('Goblin','4','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Saproling','5','G','1|1','-','Creature - Saproling','Cyril Van Der Haegen','-'),
    ('Wasp','6','-','1|1','-','Artifact Creature - Insect','Ron Spencer','Flying'),
    ('Avatar','1','W','*|*','-','Creature - Avatar','Vance Kovacs','This creature''s power and toughness are each equal to your life total.'),
    ('Elemental','2','W','4|4','-','Creature - Elemental','Anthony S. Waters','Flying'),
    ('Kithkin Soldier','3','W','1|1','-','Creature - Kithkin Soldier','Greg Hildebrandt','-'),
    ('Merfolk Wizard','4','U','1|1','-','Creature - Merfolk Wizard','Mark Poole','-'),
    ('Goblin Rogue','5','B','1|1','-','Creature - Goblin Rogue','Richard Sardinha','-'),
    ('Elemental Shaman','6','R','3|1','-','Creature - Elemental Shaman','Jim Pavelec','-'),
    ('Beast','7','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Elemental','8','G','4|4','-','Creature - Elemental','Brandon Kitkouski','-'),
    ('Elf Warrior','9','G','1|1','-','Creature - Elf Warrior','Dominick Domingo','-'),
    ('Wolf','10','G','2|2','-','Creature - Wolf','Pete Venters','-'),
    ('Shapeshifter','11','-','1|1','-','Creature - Shapeshifter','Franz Vohwinkel','Changeling'),
    ('Elemental','T1','G','7|7','-','Creature - Elemental','Anthony S. Waters','Trample'),
    ('Elf Warrior','T2','G','1|1','-','Creature - Elf Warrior','Dominick Domingo','-'),
    ('Goblin','T3','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Giant Warrior','1','W','5|5','-','Creature - Giant Warrior','Steve Ellis','-'),
    ('Faerie Rogue','2','B','1|1','-','Creature - Faerie Rogue','Jim Nelson','Flying'),
    ('Treefolk Shaman','3','G','2|5','-','Creature - Treefolk Shaman','Richard Sardinha','-'),
    ('Kithkin Soldier','1','W','1|1','-','Creature - Kithkin Soldier','Randy Gallegos','-'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Jeremy Enecio','Flying'),
    ('Rat','3','B','1|1','-','Creature - Rat','Carl Critchlow','-'),
    ('Elemental','4','R','1|1','-','Creature - Elemental','Cyril Van Der Haegen','Haste'),
    ('Elf Warrior','5','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Spider','6','G','1|2','-','Creature - Spider','Thomas M. Baxa','Reach'),
    ('Wolf','7','G','2|2','-','Creature - Wolf','Lars Grant-West','-'),
    ('Faerie Rogue','8','U B','1|1','-','Creature - Faerie Rogue','E. M. Gist','Flying'),
    ('Elemental','9','B R','5|5','-','Creature - Elemental','Dave Dorman','-'),
    ('Giant Warrior','10','R G','4|4','-','Creature - Giant Warrior','Trevor Hairsine','Haste'),
    ('Goblin Warrior','11','R G','1|1','-','Creature - Goblin Warrior','Dave Allsop','-'),
    ('Elf Warrior','12','G W','1|1','-','Creature - Elf Warrior','Carl Frank','-'),
    ('Goat','1','W','-','-','Creature - Goat','Terese Nielsen','-'),
    ('Bird','2','U','1|1','-','Creature - Bird','Heather Hudson','Flying'),
    ('Beast','3','G','3|3','-','Creature - Beast','William O''Connor','-'),
    ('Spirit','4','W B','1|1','-','Creature - Spirit','Larry MacDougall','Flying'),
    ('Elemental','5','U R','5|5','-','Creature - Elemental','Randy Gallegos','Flying'),
    ('Worm','6','B G','1|1','-','Creature - Worm','Chuck Lukacs','-'),
    ('Goblin Soldier','7','R W','1|1','-','Creature - Goblin Soldier','Jeff Miracola','-'),
    ('Soldier','1','W','1|1','-','Creature - Soldier','Alan Pollack','-'),
    ('Homunculus','2','U','-','-','Artifact Creature - Homunculus','Howard Lyon','-'),
    ('Thopter','3','U','1|1','-','Artifact Creature - Thopter','Andrew Murray','Flying'),
    ('Skeleton','4','B','1|1','-','Creature - Skeleton','Thomas M. Baxa','{B}: Regenerate this creature.'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Dave Kendall','-'),
    ('Dragon','6','R','4|4','-','Creature - Dragon','Vance Kovacs','Flying'),
    ('Goblin','7','R','1|1','-','Creature - Goblin','Brandon Kitkouski','-'),
    ('Ooze','8','G','*|*','-','Creature - Ooze','Anthony S. Waters','-'),
    ('Saproling','9','G','1|1','-','Creature - Saproling','Trevor Claxton','-'),
    ('Beast','10','R G W','8|8','-','Creature - Beast','Parente','-'),
    ('Elemental Shaman','T1','R','3|1','-','Creature - Elemental Shaman','Jim Pavelec','-'),
    ('Angel','1','W','4|4','-','Creature - Angel','Cyril Van Der Haegen','Flying'),
    ('Elemental','2','R','3|1','-','Creature - Elemental','Vance Kovacs','-'),
    ('Spirit','T1','W','1|1','-','Creature - Spirit','Luca Zontini','Flying'),
    ('Demon','T2','B','*|*','-','Creature - Demon','Pete Venters','Flying'),
    ('Thrull','T3','B','-','-','Creature - Thrull','Veronique Meignaud','-'),
    ('Bird Soldier','1','W','1|1','-','Creature - Bird Soldier','Matt Cavotta','Flying'),
    ('Lizard','2','G','2|2','-','Creature - Lizard','Anthony S. Waters','-'),
    ('Dragon','3','R G','1|1','-','Creature - Dragon','Jaime Jones','Flying‚ devour 2'),
    ('Zombie Wizard','4','U B','1|1','-','Creature - Zombie Wizard','Dave Allsop','-'),
    ('Avatar','1','W','*|*','-','Creature - Avatar','Vance Kovacs','This creature''s power and toughness are each equal to your life total.'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Parente','-'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Bud Cook','-'),
    ('Goblin','4','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Beast','5','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Insect','6','G','1|1','-','Creature - Insect','Ron Spencer','-'),
    ('Wolf','7','G','2|2','-','Creature - Wolf','Lars Grant-West','-'),
    ('Gargoyle','8','-','3|4','-','Artifact Creature - Gargoyle','Paul Bonner','Flying'),
    ('Angel','1','W','4|4','-','Creature - Angel','Adi Granov','Flying'),
    ('Bird','2','W','1|1','-','Creature - Bird','Howard Lyon','Flying'),
    ('Kor Soldier','3','W','1|1','-','Creature - Kor Soldier','Daren Bader','-'),
    ('Illusion','4','U','2|2','-','Creature - Illusion','Cyril Van Der Haegen','-'),
    ('Merfolk','5','U','1|1','-','Creature - Merfolk','Warren Mahy','-'),
    ('Vampire','6','B','*|*','-','Creature - Vampire','Kekai Kotaki','-'),
    ('Zombie Giant','7','B','5|5','-','Creature - Zombie Giant','Igor Kieryluk','-'),
    ('Elemental','8','R','7|1','-','Creature - Elemental','Anthony Francisco','Trample‚ haste'),
    ('Beast','9','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Snake','10','G','1|1','-','Creature - Snake','Austin Hsu','-'),
    ('Wolf','11','G','2|2','-','Creature - Wolf','Daren Bader','-'),
    ('Beast','T1','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Beast','T2','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Elephant','T3','G','3|3','-','Creature - Elephant','Arnie Swekel','-'),
    ('Soldier Ally','1','W','1|1','-','Creature - Soldier Ally','Kekai Kotaki','-'),
    ('Dragon','2','R','5|5','-','Creature - Dragon','Raymond Swanland','Flying'),
    ('Ogre','3','R','3|3','-','Creature - Ogre','Paul Bonner','-'),
    ('Elephant','4','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Plant','5','G','-','-','Creature - Plant','Daren Bader','-'),
    ('Construct','6','-','6|12','-','Artifact Creature - Construct','Jung Park','Trample'),
    ('Hornet','T1','-','1|1','-','Artifact Creature - Insect','Ron Spencer','Flying‚ haste'),
    ('Minion','T2','B','*|*','-','Creature - Minion','Dave Kendall','-'),
    ('Saproling','T3','G','1|1','-','Creature - Saproling','Warren Mahy','-'),
    ('Eldrazi Spawn','1a','-','-','-','Creature - Eldrazi Spawn','Aleksi Briclot','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','1b','-','-','-','Creature - Eldrazi Spawn','Mark Tedin','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','1c','-','-','-','Creature - Eldrazi Spawn','Veronique Meignaud','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Elemental','2','R','*|*','-','Creature - Elemental','Jung Park','-'),
    ('Hellion','3','R','4|4','-','Creature - Hellion','Anthony Francisco','-'),
    ('Ooze','4','G','*|*','-','Creature - Ooze','Daniel Ljunggren','-'),
    ('Tuktuk The Returned','5','-','5|5','-','Legendary Artifact Creature - Goblin Golem','Franz Vohwinkel','-'),
    ('Avatar','1','W','*|*','-','Creature - Avatar','Vance Kovacs','This creature''s power and toughness are each equal to your life total.'),
    ('Bird','2','W','3|3','-','Creature - Bird','Paul Bonner','Flying'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Bud Cook','-'),
    ('Beast','4','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Ooze','5','G','2|2','-','Creature - Ooze','Raymond Swanland','When this creature dies‚ put two 1/1 green Ooze creature tokens onto the battlefield.'),
    ('Ooze','6','G','1|1','-','Creature - Ooze','Raymond Swanland','-'),
    ('Soldier','T1','W','1|1','-','Creature - Soldier','Parente','-'),
    ('Cat','1','W','2|2','-','Creature - Cat','Scott Chou','-'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Goran Josic','-'),
    ('Goblin','3','R','1|1','-','Creature - Goblin','Goran Josic','-'),
    ('Insect','4','G','1|1','-','Creature - Insect','Adrian Smith','Infect'),
    ('Wolf','5','G','2|2','-','Creature - Wolf','Chris Rahn','-'),
    ('Golem','6','-','3|3','-','Artifact Creature - Golem','Nic Klein','-'),
    ('Myr','7','-','1|1','-','Artifact Creature - Myr','Ryan Pancoast','-'),
    ('Wurm','8','-','3|3','-','Artifact Creature - Wurm','Raymond Swanland','Deathtouch'),
    ('Wurm','9','-','3|3','-','Artifact Creature - Wurm','Raymond Swanland','Lifelink'),
    ('Poison Counter','-','-','-','-','Emblem','-','-'),
    ('Germ','1','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Zombie','2','B','2|2','-','Creature - Zombie','Dave Kendall','-'),
    ('Golem','3','-','9|9','-','Artifact Creature - Golem','Svetlin Velinov','-'),
    ('Horror','4','-','*|*','-','Artifact Creature - Horror','Scott Chou','-'),
    ('Thopter','5','-','1|1','-','Artifact Creature - Thopter','Volkan Baga','Flying'),
    ('Poison Counter','-','-','-','-','Emblem','-','-'),
    ('Goblin','T1','R','1|1','-','Creature - Goblin','Brandon Kitkouski','-'),
    ('Beast','1','G','3|3','-','Creature - Beast','Dave Allsop','-'),
    ('Goblin','2','R','1|1','-','Creature - Goblin','Jaime Jones','-'),
    ('Golem','3','-','3|3','-','Artifact Creature - Golem','Volkan Baga','-'),
    ('Myr','4','-','1|1','-','Artifact Creature - Myr','Matt Stewart','-'),
    ('Poison Counter','-','-','-','-','Emblem','-','-'),
    ('Bird','1','W','3|3','-','Creature - Bird','Paul Bonner','Flying'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Parente','-'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Carl Critchlow','-'),
    ('Beast','4','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Saproling','5','G','1|1','-','Creature - Saproling','Cyril Van Der Haegen','-'),
    ('Wurm','6','G','6|6','-','Creature - Wurm','Anthony Francisco','-'),
    ('Pentavite','7','-','1|1','-','Artifact Creature - Pentavite','Greg Staples','Flying'),
    ('Griffin','T1','W','2|2','-','Creature - Griffin','Jim Nelson','Flying'),
    ('Saproling','T2','G','1|1','-','Creature - Saproling','Cyril Van Der Haegen','-'),
    ('Angel','1','W','4|4','-','Creature - Angel','Winona Nelson','Flying'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Kev Walker','Flying'),
    ('Homunculus','3','U','2|2','-','Creature - Homunculus','Johann Bodin','-'),
    ('Demon','4','B','5|5','-','Creature - Demon','Kev Walker','Flying'),
    ('Vampire','5','B','2|2','-','Creature - Vampire','Svetlin Velinov','Flying'),
    ('Wolf','6','B','1|1','-','Creature - Wolf','Daniel Ljunggren','Deathtouch'),
    ('Zombie','7','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Zombie','8','B','2|2','-','Creature - Zombie','Christopher Moeller','-'),
    ('Zombie','9','B','2|2','-','Creature - Zombie','Cynthia Sheppard','-'),
    ('Ooze','10','G','*|*','-','Creature - Ooze','Erica Yang','This creature''s power and toughness are each equal to the number of slime counters on Gutter Grime.'),
    ('Spider','11','G','1|2','-','Creature - Spider','Daniel Ljunggren','Reach'),
    ('Wolf','12','G','2|2','-','Creature - Wolf','David Palumbo','-'),
    ('Wolf','T12','G','2|2','Judge','Creature - Wolf','David Palumbo','-'),
    ('Human','1','W','1|1','-','Creature - Human','John Stanko','-'),
    ('Vampire','2','B','1|1','-','Creature - Vampire','Peter Mohrbacher','Lifelink'),
    ('Sorin Emblem','3','-','-','-','Emblem - Sorin','Michael Komrack','Creatures you control get +1/+0.'),
    ('Checklist','C1','-','-','-','Checklist','-','You can mark this card to represent a double-faced card in your library or hand.'),
    ('Venser Emblem','E1','-','-','-','Emblem - Venser','Eric Deschamps','Whenever you cast a spell‚ exile target permanent.'),
    ('Koth Emblem','E2','-','-','-','Emblem - Koth','Eric Deschamps','Mountains you control have Tap: This land deals 1 damage to target creature or player.'''),
    ('Human','T1a','W','1|1','Full Moon','Creature - Human','Lars Grant-West','-'),
    ('Wolf','T1b','G','2|2','Full Moon','Creature - Wolf','Lars Grant-West','-'),
    ('Angel','1','W','4|4','-','Creature - Angel','Anthony Palumbo','Flying'),
    ('Human','2','W','1|1','-','Creature - Human','Michael C. Hayes','-'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Spirit','4','U','1|1','-','Creature - Spirit','Dan Scott','Flying'),
    ('Demon','5','B','5|5','-','Creature - Demon','Kev Walker','Flying'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Human','7','R','1|1','-','Creature - Human','Ryan Pancoast','Haste'),
    ('Tamiyo Emblem','8','-','-','-','Emblem - Tamiyo','Eric Deschamps','You have no maximum hand size. Whenever a card is put into your graveyard from anywhere‚ you may return it to your hand.'),
    ('Angel','T1','W','4|4','Pre-Release','Creature - Angel','James Ryman','Flying'),
    ('Angel','T1F','W','4|4','Pre-Release','Creature - Angel','James Ryman','Flying'),
    ('Demon','T5','B','5|5','Pre-Release','Creature - Demon','Karl Kopinski','Flying'),
    ('Demon','T5F','B','5|5','Pre-Release','Creature - Demon','Karl Kopinski','Flying'),
    ('Goblin','1','R','1|1','League','Creature - Goblin','Jim Nelson','-'),
    ('Cat','1','W','2|2','-','Creature - Cat','Jesper Ejsing','-'),
    ('Goat','2','W','-','-','Creature - Goat','Adam Paquette','-'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Greg Staples','-'),
    ('Drake','4','U','2|2','-','Creature - Drake','Svetlin Velinov','Flying'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Goblin','6','R','1|1','-','Creature - Goblin','Karl Kopinski','-'),
    ('Hellion','7','R','4|4','-','Creature - Hellion','Anthony Francisco','-'),
    ('Beast','8','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Saproling','9','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Wurm','10','G','6|6','-','Creature - Wurm','Anthony Francisco','-'),
    ('Liliana Emblem','11','-','-','-','Emblem - Liliana','D. Alexander Gregory','Swamps you control have Tap: Add {B}{B}{B}{B} to your mana pool.'),
    ('Saproling','T1','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Centaur','1','G','3|3','Judge','Creature - Centaur','James Ryman','-'),
    ('Knight','1','W','2|2','League','Creature - Knight','Lucas Graciano','Vigilance'),
    ('Bird','1','W','1|1','-','Creature - Bird','James Ryman','Flying'),
    ('Knight','2','W','2|2','-','Creature - Knight','Matt Stewart','Vigilance'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Steve Prescott','-'),
    ('Assassin','4','B','1|1','-','Creature - Assassin','Svetlin Velinov','Whenever this creature deals combat damage to a player‚ that player loses the game.'),
    ('Dragon','5','R','6|6','-','Creature - Dragon','Mark Zug','Flying'),
    ('Goblin','6','R','1|1','-','Creature - Goblin','Christopher Moeller','-'),
    ('Centaur','7','G','3|3','-','Creature - Centaur','Slawomir Maniak','-'),
    ('Ooze','8','G','*|*','-','Creature - Ooze','Marco Nelor','-'),
    ('Rhino','9','G','4|4','-','Creature - Rhino','Tomasz Jedruszek','Trample'),
    ('Saproling','10','G','1|1','-','Creature - Saproling','Raoul Vitale','-'),
    ('Wurm','11','G','5|5','-','Creature - Wurm','Anthony Palumbo','Trample'),
    ('Elemental','12','G W','8|8','-','Creature - Elemental','Yeong-Hao Han','Vigilance'),
    ('Soldier','1','R W','1|1','League','Creature - Soldier','Zoltan Boros','Haste'),
    ('Angel','1','W','4|4','-','Creature - Angel','Steve Argyle','Flying'),
    ('Rat','2','B','1|1','-','Creature - Rat','Nils Hamm','-'),
    ('Frog Lizard','3','G','3|3','-','Creature - Frog Lizard','Jack Wang','-'),
    ('Cleric','4','W B','1|1','-','Creature - Cleric','Jason Chan','{3}{W}{B}{B}‚ {T}‚ Sacrifice this creature: Return a card named Deathpact Angel from your graveyard to the battlefield.'),
    ('Horror','5','U B','1|1','-','Creature - Horror','Adam Paquette','Flying'),
    ('Soldier','6','R W','1|1','-','Creature - Soldier','David Palumbo','Haste'),
    ('Spirit','7','W B','1|1','-','Creature - Spirit','Cliff Childs','Flying'),
    ('Domri Emblem','8','-','-','-','Emblem - Domri','Tyler Jacobson','Creatures you control have double strike‚ trample‚ hexproof‚ and haste.'),
    ('Spirit','T1','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Bird','1','W','1|1','League','Creature - Bird','Martina Pilcerova','Flying'),
    ('Elemental','1','G W','*|*','-','Creature - Elemental','Mark Winters','This creature''s power and toughness are each equal to the number of creatures you control.'),
    ('Giant Warrior','1','W','5|5','-','Creature - Giant Warrior','Svetlin Velinov','-'),
    ('Kithkin Soldier','2','W','1|1','-','Creature - Kithkin Soldier','Randy Gallegos','-'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Goran Josic','-'),
    ('Illusion','4','U','1|1','-','Creature - Illusion','Veronique Meignaud','Flying'),
    ('Bat','5','B','1|1','-','Creature - Bat','Wayne Reynolds','Flying'),
    ('Goblin Rogue','6','B','1|1','-','Creature - Goblin Rogue','Dave Kendall','-'),
    ('Spider','7','B','2|4','-','Creature - Spider','Lars Grant-West','Reach'),
    ('Zombie','8','B','2|2','-','Creature - Zombie','Bud Cook','-'),
    ('Dragon','9','R','4|4','-','Creature - Dragon','Vance Kovacs','Flying'),
    ('Goblin','10','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Elemental','11','G','4|4','-','Creature - Elemental','Brandon Kitkouski','-'),
    ('Saproling','12','G','1|1','-','Creature - Saproling','Warren Mahy','-'),
    ('Treefolk Shaman','13','G','2|5','-','Creature - Treefolk Shaman','Zack Stella','-'),
    ('Faerie Rogue','14','U B','1|1','-','Creature - Faerie Rogue','E. M. Gist','Flying'),
    ('Worm','15','B G','1|1','-','Creature - Worm','Chuck Lukacs','-'),
    ('Elspeth Emblem','16','-','-','-','Emblem - Elspeth','Volkan Baga','Artifacts‚ creatures‚ enchantments‚ and lands you control have indestructible.'),
    ('Sliver','1','-','1|1','-','Creature - Sliver','Igor Kieryluk','-'),
    ('Angel','2','W','4|4','-','Creature - Angel','James Ryman','Flying'),
    ('Cat','3','W','2|2','-','Creature - Cat','Jesper Ejsing','-'),
    ('Goat','4','W','-','-','Creature - Goat','Adam Paquette','-'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Dragon','6','R','2|2','-','Creature - Dragon','Jack Wang','Flying {R}: This creature gets +1/+0 until end of turn.'),
    ('Elemental','7','R','1|1','-','Creature - Elemental','Jaime Jones','-'),
    ('Elemental','8','R','1|1','-','Creature - Elemental','Winona Nelson','-'),
    ('Beast','9','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Saproling','10','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Wolf','11','G','2|2','-','Creature - Wolf','Lars Grant-West','-'),
    ('Liliana Emblem','12','-','-','-','Emblem - Liliana','D. Alexander Gregory','Swamps you control have Tap: Add {B}{B}{B}{B} to your mana pool.'),
    ('Garruk Emblem','13','-','-','-','Emblem - Garruk','Karl Kopinski','Whenever you cast a creature spell‚ you may search your library for a creature card‚ put it onto the battlefield‚ then shuffle your library.'),
    ('Sliver','T1','-','1|1','League','Creature - Sliver','Vincent Proce','-'),
    ('Griffin','T1','W','2|2','-','Creature - Griffin','Johann Bodin','Flying'),
    ('Beast','T2','G','3|3','-','Creature - Beast','Jesper Ejsing','-'),
    ('Golem','1','-','3|3','Judge','Enchantment Artifact Creature - Golem','Yeong-Hao Han','-'),
    ('Soldier','1','W','1|1','League','Creature - Soldier','Johann Bodin','-'),
    ('Cleric','1','W','2|1','-','Enchantment Creature - Cleric','Johann Bodin','-'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Seb McKinnon','-'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Svetlin Velinov','-'),
    ('Bird','4','U','2|2','-','Creature - Bird','Peter Mohrbacher','Flying'),
    ('Elemental','5','U','1|0','-','Creature - Elemental','Karl Kopinski','-'),
    ('Harpy','6','B','1|1','-','Creature - Harpy','Nils Hamm','Flying'),
    ('Soldier','7','R','1|1','-','Creature - Soldier','Johann Bodin','-'),
    ('Boar','8','G','2|2','-','Creature - Boar','James Ryman','-'),
    ('Satyr','9','R G','2|2','-','Creature - Satyr','Johann Bodin','-'),
    ('Golem','10','-','3|3','-','Enchantment Artifact Creature - Golem','Yeong-Hao Han','-'),
    ('Elspeth Emblem','11','-','-','-','Emblem - Elspeth','Eric Deschamps','Creatures you control get +2/+2 and have flying.'),
    ('Soldier','1','W','1|1','League','Enchantment Creature - Soldier','Ryan Barger','-'),
    ('Bird','1','W','1|1','-','Creature - Bird','Clint Cearly','Flying'),
    ('Cat Soldier','2','W','1|1','-','Creature - Cat Soldier','Scott Chou','Vigilance'),
    ('Soldier','3','W','1|1','-','Enchantment Creature - Soldier','David Palumbo','-'),
    ('Bird','4','U','2|2','-','Enchantment Creature - Bird','Mike Sass','Flying'),
    ('Kraken','5','U','9|9','-','Creature - Kraken','Dan Scott','-'),
    ('Zombie','6','B','2|2','-','Enchantment Creature - Zombie','Winona Nelson','-'),
    ('Elemental','7','R','3|1','-','Enchantment Creature - Elemental','Greg Staples','-'),
    ('Centaur','8','G','3|3','-','Enchantment Creature - Centaur','Ryan Barger','-'),
    ('Wolf','9','G','2|2','-','Creature - Wolf','Raoul Vitale','-'),
    ('Gold','10','-','-','-','Artifact','Richard Wright','Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Kiora Emblem','11','-','-','-','Emblem - Kiora','Scott M. Fischer','At the beginning of your end step‚ put a 9/9 blue Kraken creature token onto the battlefield.'),
    ('Assassin','T1','B','1|1','-','Creature - Assassin','Svetlin Velinov','Whenever this creature deals combat damage to a player‚ that player loses the game.'),
    ('Minotaur','1','R','2|3','League','Creature - Minotaur','Scott Murphy','-'),
    ('Sphinx','1','U','4|4','-','Creature - Sphinx','Jesper Ejsing','Flying'),
    ('Zombie','2','B','*|*','-','Creature - Zombie','Zack Stella','-'),
    ('Minotaur','3','R','2|3','-','Creature - Minotaur','Craig J Spearing','-'),
    ('Hydra','4','G','*|*','-','Creature - Hydra','Steve Prescott','-'),
    ('Spider','5','G','1|3','-','Enchantment Creature - Spider','Yohann Schepacz','Reach'),
    ('Snake','6','G B','1|1','-','Enchantment Creature - Snake','Greg Staples','Deathtouch'),
    ('Soldier','1','W','1|1','-','Creature - Soldier','Goran Josic','-'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Kev Walker','Flying'),
    ('Myr','3','-','1|1','-','Artifact Creature - Myr','Matt Stewart','-'),
    ('Elspeth Emblem','4','-','-','-','Emblem - Elspeth','Volkan Baga','Artifacts‚ creatures‚ enchantments‚ and lands you control have indestructible.'),
    ('Spirit','1','W','1|1','-','Creature - Spirit','Jeff Simpson','Flying'),
    ('Demon','2','B','*|*','-','Creature - Demon','Evan Shipard','Flying'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Ogre','4','R','4|4','-','Creature - Ogre','Dave Kendall','-'),
    ('Elephant','5','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Squirrel','6','G','1|1','-','Creature - Squirrel','Daniel Ljunggren','-'),
    ('Wolf','7','G','2|2','-','Creature - Wolf','Raoul Vitale','-'),
    ('Construct','8','-','1|1','-','Artifact Creature - Construct','Adam Paquette','Defender'),
    ('Dack Emblem','9','-','-','-','Emblem - Dack','Eric Deschamps','Whenever you cast a spell that targets one or more permanents‚ gain control of those permanents.'),
    ('Wolf','1','G','2|2','Pre-Release','Creature - Wolf','David Palumbo','-'),
    ('Sliver','1','-','1|1','-','Creature - Sliver','Igor Kieryluk','-'),
    ('Squid','1','U','1|1','League','Creature - Squid','Richard Wright','Islandwalk'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Greg Staples','-'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Mike Sass','Flying'),
    ('Squid','4','U','1|1','-','Creature - Squid','Jack Wang','Islandwalk'),
    ('Beast','5','B','3|3','-','Creature - Beast','John Donahue','Deathtouch'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Dragon','7','R','2|2','-','Creature - Dragon','Jack Wang','Flying {R}: This creature gets +1/+0 until end of turn.'),
    ('Goblin','8','R','1|1','-','Creature - Goblin','Karl Kopinski','-'),
    ('Beast','9','G','3|3','-','Creature - Beast','Dave Kendall','-'),
    ('Insect','10','G','1|1','-','Creature - Insect','Martina Pilcerova','Flying‚ deathtouch'),
    ('Treefolk Warrior','11','G','*|*','-','Creature - Treefolk Warrior','Todd Lockwood','This creature''s power and toughness are each equal to the number of Forests you control.'),
    ('Land Mine','12','-','-','-','Artifact','Kev Walker','{R}‚ Sacrifice this artifact: This artifact deals 2 damage to target attacking creature without flying.'),
    ('Ajani Emblem','13','-','-','-','Emblem - Ajani','Chris Rahn','If a source would deal damage to you or a planeswalker you control‚ prevent all but 1 of that damage.'),
    ('Garruk Emblem','14','-','-','-','Emblem - Garruk','Tyler Jacobson','Whenever a creature attacks you‚ it gets +5/+5 and gains trample until end of turn.'),
    ('Goblin','82','R','1|1','-','Creature - Goblin','Karl Kopinski','-'),
    ('Warrior','1','W','1|1','League','Creature - Warrior','Winona Nelson','-'),
    ('Bird','1','W','3|4','-','Creature - Bird','Mark Zug','Flying'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Mike Sass','Flying'),
    ('Warrior','3','W','1|1','-','Creature - Warrior','Ryan Barger','-'),
    ('Warrior','4','W','1|1','-','Creature - Warrior','Yefim Kligerman','-'),
    ('Vampire','5','B','2|2','-','Creature - Vampire','Cynthia Sheppard','Flying'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Wayne Reynolds','-'),
    ('Goblin','7','R','1|1','-','Creature - Goblin','Kev Walker','-'),
    ('Bear','8','G','4|4','-','Creature - Bear','Kev Walker','-'),
    ('Snake','9','G','1|1','-','Creature - Snake','Lars Grant-West','-'),
    ('Spirit Warrior','10','B G','*|*','-','Creature - Spirit Warrior','Ryan Alexander Lee','-'),
    ('Morph','11','-','2|2','-','Creature','Raymond Swanland','(You can cover a face-down creature with this reminder card. A card with morph can be turned face up any time for its morph cost.)'),
    ('Sarkhan Emblem','12','-','-','-','Emblem - Sarkhan','Daarken','At the beginning of your draw step‚ draw two additional cards. At the beginning of your end step‚ discard your hand.'),
    ('Sorin Emblem','13','-','-','-','Emblem - Sorin','Cynthia Sheppard','At the beginning of each opponent''s upkeep‚ that player sacrifices a creature.'),
    ('Angel','1','W','4|4','-','Creature - Angel','Anthony Palumbo','Flying'),
    ('Cat','2','W','2|2','-','Creature - Cat','Scott Chou','-'),
    ('Goat','3','W','-','-','Creature - Goat','Adam Paquette','-'),
    ('Kor Soldier','4','W','1|1','-','Creature - Kor Soldier','Daren Bader','-'),
    ('Pegasus','5','W','1|1','-','Creature - Pegasus','Greg Hildebrandt','Flying'),
    ('Soldier','6','W','1|1','-','Creature - Soldier','Goran Josic','-'),
    ('Spirit','7','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Fish','8','U','3|3','-','Creature - Fish','Dan Scott','When this creature dies‚ put a 6/6 blue Whale creature token onto the battlefield with "When this creature dies‚ put a 9/9 blue Kraken creature token onto the battlefield."'),
    ('Kraken','9','U','9|9','-','Creature - Kraken','Dan Scott','-'),
    ('Whale','10','U','6|6','-','Creature - Whale','Dan Scott','When this creature dies‚ put a 9/9 blue Kraken creature token onto the battlefield.'),
    ('Zombie','11','U','*|*','-','Creature - Zombie','Dave Kendall','-'),
    ('Demon','12','B','*|*','-','Creature - Demon','Pete Venters','Flying'),
    ('Demon','13','B','5|5','-','Creature - Demon','Kev Walker','Flying'),
    ('Germ','14','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Horror','15','B','*|*','-','Creature - Horror','Jason Felix','-'),
    ('Zombie','16','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Goblin','17','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Ape','18','G','3|3','-','Creature - Ape','Lars Grant-West','-'),
    ('Beast','19','G','3|3','-','Creature - Beast','Dave Allsop','-'),
    ('Beast','20','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Elemental','21','G','5|3','-','Creature - Elemental','Nils Hamm','-'),
    ('Elephant','22','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Elf Druid','23','G','1|1','-','Creature - Elf Druid','Raymond Swanland','{T}: Add {G} to your mana pool.'),
    ('Elf Warrior','24','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Treefolk','25','G','*|*','-','Creature - Treefolk','Filip Burburan','-'),
    ('Wolf','26','G','2|2','-','Creature - Wolf','Daren Bader','-'),
    ('Gargoyle','27','-','3|4','-','Artifact Creature - Gargoyle','Paul Bonner','Flying'),
    ('Myr','28','-','1|1','-','Artifact Creature - Myr','Ryan Pancoast','-'),
    ('Pentavite','29','-','1|1','-','Artifact Creature - Pentavite','Greg Staples','Flying'),
    ('Stoneforged Blade','30','-','-','-','Artifact - Equipment','Eric Deschamps','Indestructible Equipped creature gets +5/+5 and has double strike. Equip {0}'),
    ('Tuktuk The Returned','31','-','5|5','-','Legendary Artifact Creature - Goblin Golem','Franz Vohwinkel','-'),
    ('Wurm','32','-','3|3','-','Artifact Creature - Wurm','Raymond Swanland','Deathtouch'),
    ('Wurm','33','-','3|3','-','Artifact Creature - Wurm','Raymond Swanland','Lifelink'),
    ('Teferi Emblem','34','-','-','-','Emblem - Teferi','Tyler Jacobson','You may activate loyalty abilities of planeswalkers you control on any player''s turn any time you could cast an instant.'),
    ('Nixilis Emblem','35','-','-','-','Emblem - Nixilis','Daarken','{1}{B}‚ Sacrifice a creature: You gain X life and draw X cards‚ where X is the sacrificed creature''s power.'),
    ('Daretti Emblem','36','-','-','-','Emblem - Daretti','Dan Scott','Whenever an artifact is put into your graveyard from the battlefield‚ return that card to the battlefield at the beginning of the next end step.'),
    ('Elemental','1','G','7|7','-','Creature - Elemental','Anthony S. Waters','Trample'),
    ('Elf Warrior','2','G','1|1','-','Creature - Elf Warrior','Dominick Domingo','-'),
    ('Goblin','3','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Elemental Shaman','4','R','3|1','-','Creature - Elemental Shaman','Jim Pavelec','-'),
    ('Spirit','5','W','1|1','-','Creature - Spirit','Luca Zontini','Flying'),
    ('Demon','6','B','*|*','-','Creature - Demon','Pete Venters','Flying'),
    ('Thrull','7','B','-','-','Creature - Thrull','Veronique Meignaud','-'),
    ('Beast','8','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Beast','9','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Elephant','10','G','3|3','-','Creature - Elephant','Arnie Swekel','-'),
    ('Bat','11','B','1|1','-','Creature - Bat','Wayne Reynolds','Flying'),
    ('Monk','1','W','1|1','-','Creature - Monk','Steven Belledin','Prowess'),
    ('Monk','001T','W','1|1','League','Creature - Monk','Magali Villeneuve','Prowess'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Aaron Miller','Flying'),
    ('Warrior','3','B','2|1','-','Creature - Warrior','Zoltan Boros','-'),
    ('Manifest','4','-','2|2','-','Creature','Raymond Swanland','(You can cover a face-down manifested creature with this reminder card. A manifested creature card can be turned face up any time for its mana cost. A face-down card can also be turned face up for its morph cost.)'),
    ('Soldier','66','W','1|1','-','Creature - Soldier','Svetlin Velinov','-'),
    ('Kraken','67','U','9|9','-','Creature - Kraken','Dan Scott','-'),
    ('Warrior','1','W','1|1','-','Creature - Warrior','Aaron Miller','-'),
    ('Djinn Monk','2','U','2|2','-','Creature - Djinn Monk','Izzy','Flying'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Vincent Proce','-'),
    ('Zombie Horror','4','B','*|*','-','Creature - Zombie Horror','Nils Hamm','-'),
    ('Dragon','5','R','4|4','-','Creature - Dragon','Gabor Szikszai','Flying'),
    ('Goblin','6','R','1|1','-','Creature - Goblin','Mike Bierek','-'),
    ('Morph','7','-','2|2','-','Creature','Raymond Swanland','(You can cover a face-down creature with this reminder card. A card with morph can be turned face up any time for its morph cost.)'),
    ('Narset Emblem','8','-','-','-','Emblem - Narset','Magali Villeneuve','Your opponents can''t cast noncreature spells.'),
    ('Eldrazi Spawn','1','-','-','-','Creature - Eldrazi Spawn','Aleksi Briclot','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','2','-','-','-','Creature - Eldrazi Spawn','Mark Tedin','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','3','-','-','-','Creature - Eldrazi Spawn','Veronique Meignaud','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Soldier','4','W','1|1','-','Creature - Soldier','Greg Staples','-'),
    ('Spirit','5','W','1|1','-','Creature - Spirit','Mike Sass','Flying'),
    ('Faerie Rogue','6','B','1|1','-','Creature - Faerie Rogue','Dave Allsop','Flying'),
    ('Germ','7','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Thrull','8','B','1|1','-','Creature - Thrull','Mark Tedin','-'),
    ('Elephant','9','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Insect','10','G','1|1','-','Creature - Insect','Ron Spencer','-'),
    ('Saproling','11','G','1|1','-','Creature - Saproling','Warren Mahy','-'),
    ('Snake','12','G','1|1','-','Creature - Snake','Austin Hsu','-'),
    ('Wolf','13','G','2|2','-','Creature - Wolf','Daren Bader','-'),
    ('Worm','14','B G','1|1','-','Creature - Worm','Chuck Lukacs','-'),
    ('Golem','15','-','3|3','-','Artifact Creature - Golem','Nic Klein','-'),
    ('Myr','16','-','1|1','-','Artifact Creature - Myr','Ryan Pancoast','-'),
    ('Checklist','0','-','-','-','Checklist','-','You can mark this card to represent a double-faced Planeswalker card in your library or hand.'),
    ('Angel','1','W','4|4','-','Creature - Angel','Cyril Van Der Haegen','Flying'),
    ('Knight','2','W','2|2','-','Creature - Knight','Matt Stewart','Vigilance'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Steve Prescott','-'),
    ('Demon','4','B','5|5','-','Creature - Demon','Kev Walker','Flying'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Goblin','6','R','1|1','-','Creature - Goblin','Brandon Kitkouski','-'),
    ('Ashaya‚ the Awoken World','7','G','4|4','-','Legendary Creature - Elemental','Raymond Swanland','-'),
    ('Elemental','8','G','2|2','-','Creature - Elemental','Marco Nelor','-'),
    ('Elf Warrior','9','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Thopter','10','-','1|1','-','Artifact Creature - Thopter','Adam Paquette','Flying'),
    ('Thopter','11','-','1|1','-','Artifact Creature - Thopter','Svetlin Velinov','Flying'),
    ('Jace Emblem','12','-','-','-','Emblem - Jace','Jaime Jones','Whenever you cast a spell‚ target opponent puts the top five cards of his or her library into his or her graveyard.'),
    ('Liliana Emblem','13','-','-','-','Emblem - Liliana','Karla Ortiz','Whenever a creature dies‚ return it to the battlefield under your control at the beginning of the next end step.'),
    ('Chandra Emblem','14','-','-','-','Emblem - Chandra','Eric Deschamps','At the beginning of your upkeep‚ this emblem deals 3 damage to you.'),
    ('Eldrazi Spawn','76','-','-','-','Creature - Eldrazi Spawn','Aleksi Briclot','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','77','-','-','-','Creature - Eldrazi Spawn','Veronique Meignaud','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Spawn','78','-','-','-','Creature - Eldrazi Spawn','Mark Tedin','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Hellion','79','R','4|4','-','Creature - Hellion','Anthony Francisco','-'),
    ('Plant','80','G','-','-','Creature - Plant','Daren Bader','-'),
    ('Eldrazi','1','-','10|10','-','Creature - Eldrazi','Jack Wang','-'),
    ('Eldrazi Scion','2','-','1|1','-','Creature - Eldrazi Scion','Izzy','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Scion','3','-','1|1','-','Creature - Eldrazi Scion','Winona Nelson','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Eldrazi Scion','4','-','1|1','-','Creature - Eldrazi Scion','Svetlin Velinov','Sacrifice this creature: Add {1} to your mana pool.'),
    ('Knight Ally','5','W','2|2','-','Creature - Knight Ally','Josu Hernaiz','-'),
    ('Kor Ally','6','W','1|1','-','Creature - Kor Ally','Jeremy Wilson','-'),
    ('Octopus','7','U','8|8','-','Creature - Octopus','Craig J Spearing','-'),
    ('Dragon','8','R','5|5','-','Creature - Dragon','Raymond Swanland','Flying'),
    ('Elemental','9','R','3|1','-','Creature - Elemental','Victor Adame Minguez','Trample‚ Haste'),
    ('Plant','10','G','1|1','-','Creature - Plant','Sam Burley','-'),
    ('Elemental','11','G R','5|5','-','Creature - Elemental','Brad Rigney','-'),
    ('Gideon Emblem','12','-','-','-','Emblem - Gideon','Eric Deschamps','Creatures you control get +1/+1.'),
    ('Nixilis Emblem','13','-','-','-','Emblem - Nixilis','Chris Rahn','Whenever a player draws a card‚ you lose 2 life.'),
    ('Kiora Emblem','14','-','-','-','Emblem - Kiora','Jason Chan','Whenever a creature enters the battlefield under your control‚ you may have it fight target creature.'),
    ('Experience','0','-','-','-','Emblem','-','Place your experience counters here.'),
    ('Shapeshifter','1','-','1|1','-','Creature - Shapeshifter','Franz Vohwinkel','Changeling'),
    ('Angel','2','W','4|4','-','Creature - Angel','Cyril Van Der Haegen','Flying'),
    ('Cat','3','W','2|2','-','Creature - Cat','Jesper Ejsing','-'),
    ('Knight','4','W','2|2','-','Creature - Knight','Hideaki Takamura','First strike'),
    ('Knight','5','W','2|2','-','Creature - Knight','Matt Stewart','Vigilance'),
    ('Drake','6','U','2|2','-','Creature - Drake','Svetlin Velinov','Flying'),
    ('Germ','7','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Zombie','8','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Dragon','9','R','5|5','-','Creature - Dragon','Jim Pavelec','Flying'),
    ('Elemental Shaman','10','R','3|1','-','Creature - Elemental Shaman','Jim Pavelec','-'),
    ('Lightning Ranger','11','R','5|1','-','Creature - Elemental','Svetlin Velinov','Trample‚ Haste At the beginning of your end step‚ sacrifice this creature.'),
    ('Bear','12','G','2|2','-','Creature - Bear','Heather Hudson','-'),
    ('Beast','13','G','4|4','-','Creature - Beast','Svetlin Velinov','-'),
    ('Elephant','14','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Frog Lizard','15','G','3|3','-','Creature - Frog Lizard','Jack Wang','-'),
    ('Saproling','16','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Snake','17','G','1|1','-','Creature - Snake','Dan Scott','-'),
    ('Spider','18','G','1|2','-','Creature - Spider','Daniel Ljunggren','Reach'),
    ('Wolf','19','G','2|2','-','Creature - Wolf','David Palumbo','-'),
    ('Elemental','20','U R','5|5','-','Creature - Elemental','Randy Gallegos','Flying'),
    ('Snake','21','G U','1|1','-','Creature - Snake','Christopher Moeller','-'),
    ('Spirit','22','W B','1|1','-','Creature - Spirit','Cliff Childs','Flying'),
    ('Spirit','23','W B','*|*','-','Enchantment Creature - Spirit','Adam Paquette','This creature''s power and toughness are each equal to the number of experience counters you have.'),
    ('Gold','24','-','-','-','Artifact','Richard Wright','Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Eldrazi Scion','1','-','1|1','-','Creature - Eldrazi Scion','Izzy','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Scion','2','-','1|1','-','Creature - Eldrazi Scion','Craig J Spearing','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Scion','3','-','1|1','-','Creature - Eldrazi Scion','Svetlin Velinov','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Scion','4','-','1|1','-','Creature - Eldrazi Scion','Izzy','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Scion','5','-','1|1','-','Creature - Eldrazi Scion','Winona Nelson','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Scion','6','-','1|1','-','Creature - Eldrazi Scion','Svetlin Velinov','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Angel','7','W','3|3','-','Creature - Angel','Anastasia Ovchinnikova','Flying'),
    ('Zombie','8','B','2|2','-','Creature - Zombie','Kev Walker','-'),
    ('Elemental','9','R','3|1','-','Creature - Elemental','Raymond Swanland','-'),
    ('Elemental','10','G','*|*','-','Creature - Elemental','Vincent Proce','-'),
    ('Plant','11','G','-','-','Creature - Plant','Daren Bader','-'),
    ('Angel','1','W','4|4','-','Creature - Angel','Magali Villeneuve','Flying'),
    ('Human Soldier','2','W','1|1','-','Creature - Human Soldier','Deruchenko Alexander','-'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Jason A. Engle','Flying'),
    ('Vampire Knight','4','B','1|1','-','Creature - Vampire Knight','Deruchenko Alexander','Lifelink'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Craig J Spearing','-'),
    ('Devil','6','R','1|1','-','Creature - Devil','Wayne England','When this creature dies‚ it deals 1 damage to target creature or player.'),
    ('Insect','7','G','1|1','-','Creature - Insect','Christopher Moeller','-'),
    ('Ooze','8','G','3|3','-','Creature - Ooze','Nils Hamm','-'),
    ('Wolf','9','G','2|2','-','Creature - Wolf','Aaron Miller','-'),
    ('Human Cleric','10','W B','1|1','-','Creature - Human Cleric','Min Yum','-'),
    ('Clue','11','-','-','-','Artifact - Clue','John Avon','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Clue','12','-','-','-','Artifact - Clue','Noah Bradley','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Clue','13','-','-','-','Artifact - Clue','Zezhou Chen','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Clue','14','-','-','-','Artifact - Clue','Cliff Childs','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Clue','15','-','-','-','Artifact - Clue','James Paick','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Clue','16','-','-','-','Artifact - Clue','Franz Vohwinkel','{2}‚ Sacrifice this Artifact: Draw a card.'),
    ('Jace Emblem','17','-','-','-','Emblem - Jace','Tyler Jacobson','Whenever an opponent casts his or her first spell each turn‚ counter that spell.'),
    ('Arlinn Emblem','18','-','-','-','Emblem - Arlinn','Winona Nelson','Creatures you control have haste and ''{T}: This creature deals damage equal to its power to target creature or player.'''),
    ('Checklist','CH1','-','-','-','Checklist','-','You can mark this card to represent a double-faced card in your library or hand.'),
    ('Checklist','CH2','-','-','-','Checklist','-','You can mark this card to represent a double-faced card in your library or hand.'),
    ('Spirit','1','-','1|1','-','Creature - Spirit','Daniel Ljunggren','Flying'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Greg Staples','-'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Wall','4','U','5|5','-','Creature - Wall','Brian Snoddy','Defender'),
    ('Serf','5','B','-','-','Creature - Serf','Aaron Miller','-'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Carnivore','7','R','3|1','-','Creature - Carnivore','Johann Bogan','-'),
    ('Dragon','8','R','2|2','-','Creature - Dragon','Jack Wang','Flying {R}: This creature gets +1/+0 until end of turn.'),
    ('Elemental','9','R','1|1','-','Creature - Elemental','Winona Nelson','-'),
    ('Goblin','10','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Elephant','11','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Elf Warrior','12','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Wurm','13','G','6|6','-','Creature - Wurm','Anthony Francisco','-'),
    ('Elemental','14','U R','5|5','-','Creature - Elemental','Randy Gallegos','Flying'),
    ('Goblin Soldier','15','R W','1|1','-','Creature - Goblin Soldier','Filip Burburan','-'),
    ('Dack Emblem','16','-','-','-','Emblem - Dack','Eric Deschamps','Whenever you cast a spell that targets one or more permanents‚ gain control of those permanents.'),
    ('Eldrazi Horror','1','-','3|2','-','Creature - Eldrazi Horror','Jason Felix','-'),
    ('Human Wizard','2','U','1|1','-','Creature - Human Wizard','Nils Hamm','-'),
    ('Zombie','3','B','2|2','-','Creature - Zombie','Tomasz Jedruszek','-'),
    ('Zombie','4','B','2|2','-','Creature - Zombie','Seb McKinnon','-'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Anna Steinbauer','-'),
    ('Zombie','6','B','*|*','-','Creature - Zombie','Daarken','-'),
    ('Human','7','R','1|1','-','Creature - Human','Kieran Yanner','-'),
    ('Spider','8','G','1|2','-','Creature - Spider','Christine Choi','Reach'),
    ('Liliana Emblem','9','-','-','-','Emblem - Liliana','Anna Steinbauer','At the beginning of your end step‚ put X 2/2 black Zombie creature tokens onto the battlefield‚ where X is two plus the number of Zombies you control.'),
    ('Tamiyo Emblem','10','-','-','-','Emblem - Tamiyo','Tianhua X','You may cast nonland cards from your hand without paying their mama costs.'),
    ('Checklist','CH1','-','-','-','Checklist','-','You can mark this card to represent a double-faced card in your library or hand.'),
    ('The Monarch','1','-','-','-','Emblem','Mike Bierek','At the beginning of the monarch''s end step‚ that player draws a card. Whenever a creature deals combat damage to the monarch‚ its controller becomes the monarch.'),
    ('Soldier','2','W','1|1','-','Creature - Soldier','Greg Staples','-'),
    ('Soldier','3','W','1|2','-','Creature - Soldier','Jason A. Engle','Defender'),
    ('Spirit','4','W','1|1','-','Creature - Spirit','Jeff Simpson','Flying'),
    ('Assassin','5','B','1|1','-','Creature - Assassin','Josu Hernaiz','Deathtouch‚ haste'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Seb McKinnon','-'),
    ('Dragon','7','R','5|5','-','Creature - Dragon','Raymond Swanland','Flying'),
    ('Goblin','8','R','1|1','-','Creature - Goblin','Jason A. Engle','This creature can''t block.'),
    ('Lizard','9','R','8|8','-','Creature - Lizard','Filip Burburan','-'),
    ('Beast','10','G','3|3','-','Creature - Beast','Jesper Ejsing','-'),
    ('Insect','11','G','1|1','-','Creature - Insect','Carl Critchlow','-'),
    ('Construct','12','-','1|1','-','Artifact Creature - Construct','Victor Adame Minguez','Defender'),
    ('Eldrazi Scion','71','-','1|1','-','Creature - Eldrazi Scion','Izzy','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Demon','72','B','5|5','-','Creature - Demon','Kev Walker','Flying'),
    ('Zombie Giant','73','B','5|5','-','Creature - Zombie Giant','Igor Kieryluk','-'),
    ('Elemental','74','G','4|4','-','Creature - Elemental','Brandon Kitkouski','-'),
    ('Plant','75','G','-','-','Creature - Plant','Daren Bader','-'),
    ('Nixilis Emblem','76','-','-','-','Emblem - Nixilis','Raymond Swanland','Whenever a player draws a card‚ you lose 2 life.'),
    ('Beast','1','-','6|6','-','Artifact Creature - Beast','Sara Winters','-'),
    ('Construct','2','-','*|*','-','Artifact Creature - Construct','Magali Villeneuve','-'),
    ('Construct','3','-','*|*','-','Artifact Creature - Construct','Kieran Yanner','-'),
    ('Servo','4','-','1|1','-','Artifact Creature - Servo','Igor Kieryluk','-'),
    ('Servo','5','-','1|1','-','Artifact Creature - Servo','Victor Adame Minguez','-'),
    ('Servo','6','-','1|1','-','Artifact Creature - Servo','Jung Park','-'),
    ('Thopter','7','-','1|1','-','Artifact Creature - Thopter','Adam Paquette','Flying'),
    ('Thopter','8','-','1|1','-','Artifact Creature - Thopter','Svetlin Velinov','Flying'),
    ('Thopter','9','-','1|1','-','Artifact Creature - Thopter','Richard Wright','Flying'),
    ('Chandra Emblem','10','-','-','-','Emblem - Chandra','Magali Villeneuve','Whenever you cast a spell this emblem deals 5 damage to target creature or player.'),
    ('Nissa Emblem','11','-','-','-','Emblem - Nissa','Clint Cearly','Whenever a land enters the battlefield under your control you may draw a card.'),
    ('Dovin Emblem','12','-','-','-','Emblem - Dovin','Tyler Jacobson','You opponents can''t untap more than two permanents during their untap steps.'),
    ('Energy Reserve','-','-','-','-','Emblem','-','Place your energy counters in this area.'),
    ('Spirit','1','-','1|1','-','Creature - Spirit','Hugh Jamieson','Flying'),
    ('Bird','2','W','1|1','-','Creature - Bird','Winona Nelson','Flying'),
    ('Elemental','3','W','4|4','-','Creature - Elemental','Anthony S. Waters','Flying'),
    ('Goat','4','W','-','-','Creature - Goat','Adam Paquette','-'),
    ('Soldier','5','W','1|1','-','Creature - Soldier','Seb McKinnon','-'),
    ('Spirit','6','W','1|1','-','Creature - Spirit','Mike Sass','Flying'),
    ('Bird','7','U','2|2','-','Creature - Bird','Peter Mohrbacher','Flying'),
    ('Squid','8','U','1|1','-','Creature - Squid','Jack Wang','Islandwalk'),
    ('Thopter','9','U','1|1','-','Artifact Creature - Thopter','Andrew Murray','Flying'),
    ('Germ','10','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Zombie','11','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Goblin','12','R','1|1','-','Creature - Goblin','Wayne Reynolds','Creatures you control attack each combat if able.'),
    ('Ogre','13','R','3|3','-','Creature - Ogre','Paul Bonner','-'),
    ('Beast','14','G','3|3','-','Creature - Beast','Jesper Ejsing','-'),
    ('Elf Warrior','15','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Saproling','16','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Saproling','17','G','1|1','-','Creature - Saproling','Raoul Vitale','-'),
    ('Worm','18','B G','1|1','-','Creature - Worm','Chuck Lukacs','-'),
    ('Horror','19','-','*|*','-','Artifact Creature - Horror','Scott Chou','-'),
    ('Myr','20','-','1|1','-','Artifact Creature - Myr','Ryan Pancoast','-'),
    ('Daretti Emblem','21','-','-','-','Emblem - Daretti','Dan Scott','Whenever an artifact is put into your graveyard from the battlefield‚ return that card to the battlefield at the beginning of the next end step.'),
    ('Eldrazi','1','-','7|7','-','Creature - Eldrazi','Vincent Proce','Annihilator 1 (Whenever this creature attacks‚ defending player sacrifices a permanant.)'),
    ('Eldrazi Spawn','2','-','-','-','Creature - Eldrazi Spawn','Aleksi Briclot','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Spawn','3','-','-','-','Creature - Eldrazi Spawn','Mark Tedin','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Eldrazi Spawn','4','-','-','-','Creature - Eldrazi Spawn','Veronique Meignaud','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Angel','5','W','4|4','-','Creature - Angel','Cyril Van Der Haegen','Flying'),
    ('Goat','6','W','-','-','Creature - Goat','Terese Nielsen','-'),
    ('Germ','7','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Spider','8','B','2|4','-','Creature - Spider','Lars Grant-West','Reach'),
    ('Zombie','9','B','2|2','-','Creature - Zombie','Dave Kendall','-'),
    ('Dragon','10','R','5|5','-','Creature - Dragon','Jim Pavelec','Flying'),
    ('Goblin','11','R','1|1','-','Creature - Goblin','Brandon Kitkouski','-'),
    ('Hellion','12','R','4|4','-','Creature - Hellion','Anthony Francisco','-'),
    ('Beast','13','G','3|3','-','Creature - Beast','Dave Allsop','-'),
    ('Boar','14','G','3|3','-','Creature - Boar','Jesper Ejsing','-'),
    ('Insect','15','G','1|1','-','Creature - Insect','Carl Critchlow','-'),
    ('Ooze','16','G','1|1','-','Creature - Ooze','Raymond Swanland','-'),
    ('Ooze','17','G','2|2','-','Creature - Ooze','Raymond Swanland','When this creature dies‚ put two 1/1 green Ooze creature tokens onto the battlefield.'),
    ('Plant','18','G','-','-','Creature - Plant','Daren Bader','-'),
    ('Saproling','19','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Gremlin','1','R','2|2','-','Creature - Gremlin','Jason Rainville','-'),
    ('Ragavan','2','R','2|1','-','Legendary Creature - Monkey','Daniel Ljunggren','-'),
    ('Etherium Cell','3','-','-','-','Artifact','Craig J Spearing','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Tezzeret Emblem','4','-','-','-','Emblem - Tezzeret','Ryan Alexander Lee','At the begining of combat on your turn‚ target artifact you control becomes an artifact creature with base power and toughness 5/5.'),
    ('Angel','1','W','4|4','-','Creature - Angel','Anthony Palumbo','Flying'),
    ('Bird','2','W','1|1','-','Creature - Bird','James Ryman','Flying'),
    ('Soldier','3','W','1|1','-','Creature - Soldier','Magali Villeneuve','-'),
    ('Spirit','4','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Spider','5','B','2|4','-','Creature - Spider','Lars Grant-West','Reach'),
    ('Zombie','6','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Dragon','7','R','4|4','-','Creature - Dragon','Vance Kovacs','Flying'),
    ('Goblin','8','R','1|1','-','Creature - Goblin','Brandon Kitkouski','-'),
    ('Beast','9','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Beast','10','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Centaur','11','G','3|3','-','Creature - Centaur','Slawomir Maniak','-'),
    ('Elephant','12','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Ooze','13','G','*|*','-','Creature - Ooze','Marco Nelor','-'),
    ('Saproling','14','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Wurm','15','G','5|5','-','Creature - Wurm','Anthony Palumbo','Trample'),
    ('Elemental','16','G W','*|*','-','Creature - Elemental','Mark Winters','This creature''s power and toughness are each equal to the number of creatures you control.'),
    ('Giant Warrior','17','R G','4|4','-','Creature - Giant Warrior','Trevor Hairsine','Haste'),
    ('Goblin Warrior','18','R G','1|1','-','Creature - Goblin Warrior','Dave Allsop','-'),
    ('Soldier','19','R W','1|1','-','Creature - Soldier','David Palumbo','-'),
    ('Golem','20','-','3|3','-','Artifact Creature - Golem','Volkan Baga','-'),
    ('Domri Emblem','21','-','-','-','Emblem - Domri','Tyler Jacobson','Creatures you control have double strike‚ trample‚ hexproof‚ and haste.'),
    ('Drake','1','U','2|2','-','Creature - Drake','Svetlin Velinov','Flying'),
    ('Elemental','2','R','1|1','-','Creature - Elemental','Winona Nelson','-'),
    ('Goblin','3','R','1|1','-','Creature - Goblin','Dave Kendall','-'),
    ('Beast','4','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Elephant','5','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Elf Warrior','6','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Wurm','7','G','6|6','-','Creature - Wurm','Anthony Francisco','-'),
    ('Angel of Sanctions','1','W','3|4','-','Creature - Zombie Angel','Min Yum','Flying When Angel of Sanctions enters the battlefield‚ you may exile target nonland permanent an opponent controls until Angel of Sanctions leaves the battlefield.'),
    ('Anointer Priest','2','W','1|3','-','Creature - Zombie Human Cleric','Lake Hurwitz','Whenever a creature token enters the battlefield under your control‚ you gain 1 life.'),
    ('Aven Initiate','3','W','3|2','-','Creature - Zombie Bird Warrior','Jakub Kasper','Flying'),
    ('Aven Wind Guide','4','W','2|3','-','Creature - Zombie Bird Warrior','Sidharth Chaturvedi','Flying‚ vigilance Creature tokens you control have flying and vigilance.'),
    ('Glyph Keeper','5','W','5|3','-','Creature - Zombie Sphinx','Chris Rahn','Flying Whenever Glyph Keeper becomes the target of a spell or ability for the first time each turn‚ counter that spell or ability.'),
    ('Heart-Piercer Manticore','6','W','4|3','-','Creature - Zombie Manticore','Scott Murphy','When Heart-Piercer Manticore enters the battlefield‚ you may sacrifice another creature. When you do‚ Heart-Piercer Manticore deals damage equal to that creature''s power to target creature or player.'),
    ('Honored Hydra','7','W','6|6','-','Creature - Zombie Snake Hydra','Todd Lockwood','Trample'),
    ('Labyrinth Guardian','8','W','2|3','-','Creature - Zombie Illusion Warrior','Yeong-Hao Han','When Labyrinth Guardian becomes the target of a spell‚ sacrifice it.'),
    ('Oketra''s Attendant','9','W','3|3','-','Creature - Zombie Bird Soldier','Lake Hurwitz','Flying'),
    ('Sacred Cat','10','W','1|1','-','Creature - Zombie Cat','Zezhou Chen','Lifelink'),
    ('Tah-Crop Skirmisher','11','W','2|1','-','Creature - Zombie Naga Warrior','Victor Adame Minguez','-'),
    ('Temmet‚ Vizier of Naktamun','12','W','2|2','-','Creature - Zombie Human Cleric','Anna Steinbauer','Temmet‚ Vizier of Naktamun is legendary. At the beginning of combat on your turn‚ target creature token you control gets +1/+1 until end of turn and can''t be blocked this turn.'),
    ('Trueheart Duelist','13','W','2|2','-','Creature - Zombie Human Warrior','Izzy','Trueheart Duelist can block an additional creature each combat.'),
    ('Unwavering Initiate','14','W','3|2','-','Creature - Zombie Human Warrior','Greg Opalinski','Vigilance'),
    ('Vizier of Many Faces','15','W','-','-','Creature - Zombie Shapeshifter Cleric','Ryan Yee','You may have Vizier of Many Faces enter the battlefield as a copy of any creature on the battlefield‚ except it has no mana cost‚ it''s white‚ and it''s a Zombie in addition to its other types.'),
    ('Cat','16','W','1|1','-','Creature - Cat','Filip Burburan','Lifelink'),
    ('Warrior','17','W','1|1','-','Creature - Warrior','Magali Villeneuve','Vigilance'),
    ('Drake','18','U','2|2','-','Creature - Drake','John Severin Brassell','Flying'),
    ('Insect','19','B','1|1','-','Creature - Insect','Jason A. Engle','-'),
    ('Zombie','20','B','2|2','-','Creature - Zombie','Igor Kieryluk','-'),
    ('Beast','21','G','4|2','-','Creature - Beast','Kieran Yanner','-'),
    ('Hippo','22','G','3|3','-','Creature - Hippo','Zack Stella','-'),
    ('Snake','23','G','1|1','-','Creature - Snake','Tyler Jacobson','Deathtouch'),
    ('Wurm','24','G','5|5','-','Creature - Wurm','Slawomir Maniak','-'),
    ('Gideon Emblem','25','-','-','-','Emblem - Gideon','Izzy','As long as you control a Gideon planeswalker‚ you can''t lose the game and your opponents can''t win the game.'),
    ('Punch card','-','-','-','-','Punch card','-','-'),
    ('Kithkin Soldier','1','W','1|1','-','Creature - Kithkin Soldier','Randy Gallegos','-'),
    ('Knight','2','W','2|2','-','Creature - Knight','Matt Stewart','Vigilance'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Germ','4','B','-','-','Creature - Germ','Igor Kieryluk','-'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Lucas Graciano','-'),
    ('Dragon','6','R','5|5','-','Creature - Dragon','Jim Pavelec','Flying'),
    ('Beast','7','G','3|3','-','Creature - Beast','Dave Allsop','-'),
    ('Beast','8','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Elemental','9','G','5|3','-','Creature - Elemental','Nils Hamm','-'),
    ('Elephant','10','G','3|3','-','Creature - Elephant','Lars Grant-West','-'),
    ('Elf Druid','11','G','1|1','-','Creature - Elf Druid','Raymond Swanland','{T}: Add {G} to your mana pool.'),
    ('Elf Warrior','12','G','1|1','-','Creature - Elf Warrior','William O''Connor','-'),
    ('Saproling','13','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Spider','14','G','1|2','-','Creature - Spider','Daniel Ljunggren','Reach'),
    ('Treefolk','15','G','*|*','-','Creature - Treefolk','Filip Burburan','-'),
    ('Wolf','16','G','2|2','-','Creature - Wolf','Daren Bader','-'),
    ('Wolf','17','G','2|2','-','Creature - Wolf','David Palumbo','-'),
    ('Drake','18','G U','2|2','-','Creature - Drake','Nick Percival','Flying'),
    ('Gargoyle','19','-','3|4','-','Artifact Creature - Gargoyle','Paul Bonner','Flying'),
    ('Soldier','1','W','1|1','-','Creature - Soldier','Steve Prescott','-'),
    ('Spirit','2','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Horror','3','B','3|3','-','Creature - Horror','Grzegorz Rutkowski','-'),
    ('Beast','4','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Beast','5','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Adorned Pouncer','1','B','4|4','-','Creature - Zombie Cat','Slawomir Maniak','Double strike'),
    ('Champion of Wits','2','B','4|4','-','Creature - Zombie Naga Wizard','Even Amundsen','When Champion of Wits enters the battlefield‚ you may draw cards equal to its power. If you do‚ discard two cards.'),
    ('Dreamstealer','3','B','4|4','-','Creature - Zombie Human Wizard','Yongjae Choi','Menace Whenever Dreamstealer deals combat damage to a player‚ that player discards that many cards.'),
    ('Earthshaker Khenra','4','B','4|4','-','Creature - Zombie Jackal Warrior','Jason A. Engle','Haste When Earthshaker Khenra enters the battlefield‚ target creature with power less than or equal to Earthshaker Khenra’s power can’t block this turn.'),
    ('Proven Combatant','5','B','4|4','-','Creature - Zombie Human Warrior','Clint Cearley','-'),
    ('Resilient Khenra','6','B','4|4','-','Creature - Zombie Jackal Wizard','Svetlin Velinov','When Resilient Khenra enters the battlefield‚ you may have target creature get +X/+X until end of turn‚ where X is Resilient Khenra’s power.'),
    ('Sinuous Striker','7','B','4|4','-','Creature - Zombie Naga Warrior','Svetlin Velinov','{U}: Sinuous Striker gets +1/-1 until end of turn.'),
    ('Steadfast Sentinel','8','B','4|4','-','Creature - Zombie Human Cleric','Karl Kopinski','Vigilance'),
    ('Sunscourge Champion','9','B','4|4','-','Creature - Zombie Human Wizard','Josu Hernaiz','When Sunscourge Champion enters the battlefield‚ you gain life equal to its power.'),
    ('Horse','10','W','5|5','-','Creature - Horse','Lucas Graciano','-'),
    ('Snake','11','G','5|4','-','Creature - Snake','Winona Nelson','-'),
    ('Insect','12','U R','1|1','-','Creature - Insect','Lius Lasahido','Flying‚ haste'),
    ('Punch card','-','-','-','-','Punch card','-','-'),
    ('Cat','1','W','2|2','-','Creature - Cat','Scott Chou','-'),
    ('Bat','2','B','1|1','-','Creature - Bat','Wayne Reynolds','Flying'),
    ('Rat','3','B','1|1','-','Creature - Rat','Shreya Shetty','Deathtouch'),
    ('Vampire','4','B','1|1','-','Creature - Vampire','Volkan Baga','-'),
    ('Zombie','5','B','2|2','-','Creature - Zombie','Craig J Spearing','-'),
    ('Dragon','6','R','4|4','-','Creature - Dragon','Vance Kovacs','Flying'),
    ('Dragon','7','R','6|6','-','Creature - Dragon','Mark Zug','Flying'),
    ('Cat Warrior','8','G','2|2','-','Creature - Cat Warrior','Michael Sutfin','Forestwalk'),
    ('Cat Dragon','9','B R G','3|3','-','Creature - Cat Dragon','Cynthia Sheppard','Flying'),
    ('Gold','10','-','-','-','Artifact','Richard Wright','Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Eldrazi Spawn','11','-','-','-','Creature - Eldrazi Spawn','Aleksi Briclot','Sacrifice this creature: Add {OX} to your mana pool.'),
    ('Vampire','1','W','1|1','-','Creature - Vampire','John Severin Brassell','Lifelink (Damage dealt by this creature also causes you to gain that much life.)'),
    ('Merfolk','001 P FNM','U','1|1','FNM','Creature - Merfolk','Randy Gallegos','Hexproof (This creature can’t be the target of spells or abilities your opponents control.)'),
    ('Treasure','001 P FNM','-','-','FNM','Artifact - Treasure','Jason Felix','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Illusion','2','U','2|2','-','Creature - Illusion','Noah Bradley','When this creature becomes the target of a spell‚ sacrifice it.'),
    ('Merfolk','3','U','1|1','-','Creature - Merfolk','Randy Gallegos','Hexproof (This creature can’t be the target of spells or abilities your opponents control.)'),
    ('Illusion','003 P FNM','U','2|2','FNM','Creature - Illusion','Noah Bradley','When this creature becomes the target of a spell‚ sacrifice it.'),
    ('Pirate','4','B','2|2','-','Creature - Pirate','Matt Stewart','Menace (This creature can’t be blocked except by two or more creatures.)'),
    ('Dinosaur','5','G','3|3','-','Creature - Dinosaur','Filip Burburan','Trample (This creature can deal excess combat damage to defending player or planeswalker while attacking.)'),
    ('Plant','6','G','-','-','Creature - Plant','Florian de Gesincourt','Defender (This creature can’t attack.)'),
    ('Treasure','7','-','-','-','Artifact - Treasure','Florian de Gesincourt','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Treasure','8','-','-','-','Artifact - Treasure','Zoltan Boros','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Treasure','9','-','-','-','Artifact - Treasure','Jason Felix','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Treasure','10','-','-','-','Artifact - Treasure','Milivoj Ćeran','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Vampire','010 P FNM','W','1|1','FNM','Creature - Vampire','John Severin Brassell','Lifelink'),
    ('Treasure','010 P FNM','-','-','FNM','Artifact - Treasure','Zoltan Boros','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Dinosaur','011 P FNM','G','3|3','FNM','Creature - Dinosaur','Filip Burburan','Trample'),
    ('Treasure','011 P FNM','-','-','FNM','Artifact - Treasure','Florian de Gesincourt','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Pirate','012 P FNM','B','2|2','FNM','Creature - Pirate','Matt Stewart','Menace'),
    ('Treasure','012 P FNM','-','-','FNM','Artifact - Treasure','Milivoj Ćeran','{T}‚ Sacrifice this artifact: Add one mana of any color to your mana pool.'),
    ('Checklist','CH1','-','-','-','Checklist','-','You can mark this card to represent a double-faced card in your library or hand.'),
    ('Elemental','1','U','1|0','-','Creature - Elemental','Svetlin Velinov','-'),
    ('Goblin','2','R','1|1','-','Creature - Goblin','Karl Kopinski','-'),
    ('Wall','3','U','5|5','-','Creature - Wall','Brian Snoddy','Defender'),
    ('Angel','1','W','4|4','-','Creature - Angel','Magali Villeneuve','Flying'),
    ('Bird','2','W','1|1','-','Creature - Bird','Howard Lyon','Flying'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Ryan Yee','Flying'),
    ('Djinn Monk','4','U','2|2','-','Creature - Djinn Monk','Izzy','Flying'),
    ('Dragon','5','R','2|2','-','Creature - Dragon','Jack Wang','Flying {R}: This creature gets +1/+0 until end of turn.'),
    ('Dragon','6','R','5|5','-','Creature - Dragon','Jim Pavelec','Flying'),
    ('Beast','7','G','4|4','-','Creature - Beast','Steve Prescott','-'),
    ('Angel','1','W','4|4','-','Creature - Angel','Magali Villeneuve','Flying'),
    ('Angel','001','B-W','4|4','-','Creature - Angel','Magali Villeneuve','Flying'),
    ('Goat','2','W','-','-','Creature - Goat','Carl Critchlow','-'),
    ('Spirit','3','W','1|1','-','Creature - Spirit','Jason A. Engle','Flying'),
    ('Spirit','003 B','W','1|1','-','Creature - Spirit','Jason A. Engle','Flying'),
    ('Faerie Spy','4','U','1|1','-','Creature - Faerie Spy','Dmitry Burmak','Flying‚ haste Whenever this creature deals combat damage to a player‚ draw a card.'),
    ('Storm Crow','5','U','1|2','-','Creature - Bird','McLean Kendree','Flying'),
    ('Thopter','6','U','1|1','-','Artifact Creature - Thopter','Andrew Murray','Flying'),
    ('Thopter','006 B','U','1|1','-','Artifact Creature - Thopter','Andrew Murray','Flying'),
    ('Rogue','7','B','2|2','-','Creature - Rogue','Emrah Elmasli','Menace'),
    ('Vampire','8','B','2|2','-','Creature - Vampire','Svetlin Velinov','Flying'),
    ('Vampire','008 B','B','2|2','-','Creature - Vampire','Svetlin Velinov','Flying'),
    ('Zombie','9','B','2|2','-','Creature - Zombie','Craig J Spearing','-'),
    ('Zombie','009 B','B','2|2','-','Creature - Zombie','Craig J Spearing','-'),
    ('Brainiac','10','R','1|1','-','Creature - Brainiac','Matt Dixon','-'),
    ('Elemental','11','R','1|1','-','Creature - Elemental','Winona Nelson','-'),
    ('Elemental','011 B','R','1|1','-','Creature - Elemental','Winona Nelson','-'),
    ('Goblin','12','R','1|1','-','Creature - Goblin','Dave Allsop','-'),
    ('Beast','13','G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Beast','013', 'B G','3|3','-','Creature - Beast','John Donahue','-'),
    ('Saproling','14','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Saproling','014 B','G','1|1','-','Creature - Saproling','Brad Rigney','-'),
    ('Squirrel','15','G','1|1','-','Creature - Squirrel','John Thacker','-'),
    ('Dragon','16','W U B R G','4|4','-','Creature - Dragon','Autumn Rain Turkel','Flying'),
    ('Elemental','17','G W','*|*','-','Creature - Elemental','Mark Winters','This creature’s power and toughness are each equal to the number of creatures you control.'),
    ('Elemental','017','B G W','*|*','-','Creature - Elemental','Mark Winters','This creature’s power and toughness are each equal to the number of creatures you control.'),
    ('Clue','18','-','-','-','Artifact - Clue','John Avon','{2}‚ Sacrifice this artifact: Draw a card.'),
    ('Clue','018 B','-','-','-','Artifact - Clue','John Avon','{2}‚ Sacrifice this artifact: Draw a card.'),
    ('Construct','19','-','*|*','-','Artifact Creature - Construct','Matt Gaser','-'),
    ('Gnome','20','-','1|1','-','Artifact Creature - Gnome','Dmitry Burmak','-'),
    ('Elemental','1','R','-','-','Creature - Elemental','Jason Rainville','At the beginning of your upkeep‚ sacrifice this creature and return target card named Rekindling Phoenix from your graveyard to the battlefield. It gains haste until end of turn.'),
    ('Elemental','2','R','1|1','-','Creature - Elemental','Lius Lasahido','-'),
    ('City''s Blessing','002 P FNM','-','-','FNM','Emblem','Yeong-Hao Han','-'),
    ('Elemental','002 P FNM','R','-','FNM','Creature - Elemental','Jason Rainville','At the beginning of your upkeep‚ sacrifice this creature and return target card named Rekindling Phoenix from your graveyard to the battlefield. It gains haste until end of turn.'),
    ('Saproling','3','G','1|1','-','Creature - Saproling','Joseph Meehan','-'),
    ('Saproling','003 P FNM','G','1|1','FNM','Creature - Saproling','Joseph Meehan','-'),
    ('Golem','4','-','4|4','-','Artifact Creature - Golem','Svetlin Velinov','-'),
    ('Huatli Emblem','5','-','-','-','Emblem - Huatli','Chris Rahn','Whenever a creature enters the battlefield under your control‚ you may draw a card.'),
    ('City''s Blessing','6','-','-','-','Emblem','Yeong-Hao Han','-'),
    ('Boar','','G','2/2','-','-','Creature>Beast','https://tokens.mtg.onl/tokens/THS_8-Boar.jpg'),
    ('Dragon','','G','6/6','-','Flying','Creature>Dragon','https://tokens.mtg.onl/tokens/C17_007-Dragon.jpg'),
    ('Eldrazi','','B','10/10','-','Creeper','Creature>Eldrazi','https://tokens.mtg.onl/tokens/BFZ_001-Eldrazi.jpg'),
    ('Goblin','','B','1/1','-','Kneecapper','Creature>Goblin','https://tokens.mtg.onl/tokens/EVG_T3-Goblin.jpg')
;

insert into token_logs (game_id, player_id, token_id)
values (1,4,3),(1,4,4),(1,4,4),(2,2,1),(2,2,4),(4,3,3),(4,3,1),(4,2,4),(5,2,1),(5,4,4),(5,2,4);

insert into results (game_id, player_id, outcome, life, duration)
values (1,4,'W', 12,'00:25:30'),(1,4,'L', 0,'00:17:45'),(1,4,'W', 15,'00:25:30'),(2,2,'L', 0,'00:18:00'),(2,2,'W', 12,'00:17:45'),
(4,3,'L', 0,'00:18:00'),(4,3,'W', 19,'00:18:00'),(4,2,'L', 0,'00:25:30'),(5,2,'W', 5,'00:17:45'),(5,4,'L',0,'00:25:30'),(5,2,'L', 0,'00:18:00');

select * from users;
select * from players;
select * from games;
select * from tokens;
select * from token_logs;
select * from results;